[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "isocodes"
version = "2023.11.26"
description = "This project provides lists of various ISO standards (e.g. country, language, language scripts, and currency names) in one place"
authors = [{ name = "Atem18", email = "contact@atemlire.io" }]
license = { file = "LICENSE" }
readme = "README.md"
homepage = "https://github.com/Atem18/isocodes"
repository = "https://github.com/Atem18/isocodes"
keywords = ["iso"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = []

[project.optional-dependencies]

dev = ["pre-commit == 3.6.0", "ruff == 0.1.8", "mypy == 1.7.1"]

doc = ["mkdocs == 1.5.3", "mkdocs-material == 9.5.2", "mkdocstrings == 0.24.0"]

test = [
    "pytest == 7.4.3",
    "tox == 4.11.4",
    "pyinstaller[hook_testing] == 6.3.0",
    "psutil == 5.9.7",
]

build = ["hatch == 1.9.1"]

[project.entry-points.pyinstaller40]
hook-dirs = "isocodes.__pyinstaller:get_hook_dirs"
tests = "isocodes.__pyinstaller:get_hook_dirs"
