[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "isocodes"
version = "2023.06.24"
description = "This project provides lists of various ISO standards (e.g. country, language, language scripts, and currency names) in one place"
authors = [{ name = "Atem18", email = "contact@atemlire.io" }]
license = { file = "LICENSE" }
readme = "README.md"
homepage = "https://github.com/Atem18/isocodes"
repository = "https://github.com/Atem18/isocodes"
keywords = ["iso"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
]
dependencies = []

[project.optional-dependencies]
dev = ["pre-commit >=2.17.0,<4.0.0", "ruff == 0.0.278", "mypy == 1.4.1"]

doc = ["mkdocs == 1.4.3", "mkdocs-material == 9.1.15", "mkdocstrings == 0.22.0"]

test = ["pytest == 7.4.0", "tox == 4.6.4"]

build = ["hatch == 1.7.0"]
