name: Test iso-codes
on: [pull_request]
jobs:
  publish_test:
    uses: ./.github/workflows/publish-test.yaml
  pytest:
    name: Run tests
    needs: [publish_test]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: pip install -r requirements/test-requirements.txt
      - name: Run Tox
        run: tox -e py
